# Generated by Django 2.0.7 on 2018-08-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180806_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.IntegerField(default=0),
        ),
    ]
