# Generated by Django 2.0.7 on 2018-08-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_location_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='parent',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
